SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET AUTOCOMMIT = 0;
START TRANSACTION;
SET time_zone = "+07:00";

/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

CREATE DATABASE IF NOT EXISTS `fat-school` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;
USE `fat-school`;

CREATE TABLE IF NOT EXISTS `roles` (
  `code` int(2) NOT NULL,
  `position` varchar(100) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `users` (
  `user_id` varchar(10) NOT NULL,
  `user_name` varchar(200) NOT NULL,
  `password` varchar(100) NOT NULL,
  `user_image` VARCHAR(200) NOT NULL,
  `day_of_birth` date NOT NULL,
  `user_email` varchar(200) NOT NULL,
  `user_phone` varchar(12) NOT NULL,
  `user_address` varchar(500) NOT NULL,
  `user_role` int(2) NOT NULL,
  `user_state` tinyint(1) NOT NULL DEFAULT '0',
  `created_at` DATETIME(6) NOT NULL,
  `updated_at` DATETIME(6) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;


ALTER TABLE `roles`
  ADD PRIMARY KEY (`code`);

ALTER TABLE `users`
  ADD PRIMARY KEY (`user_id`),
  ADD KEY `FK_user_role` (`user_role`);


ALTER TABLE `users`
  ADD CONSTRAINT `FK_user_role` FOREIGN KEY (`user_role`) REFERENCES `roles` (`code`) ON UPDATE CASCADE;
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
